### ISSUE TITLE
Add compatibility for CruiserImproved

### ISSUE THREAD

**Issue by Jaco909** [wongnata/PlayerDogModel_Plus#51]
The [CruiserImproved](https://thunderstore.io/c/lethal-company/p/DiggC/CruiserImproved/) mod conflicts with the camera adjustments from this mod. When equipping the dog suit, the camera attempts to move down, but is continuously snapped back to the default position. This causes a constant vibrating effect for the player's camera.

Not sure if that's something that can be fixed with this mod or with the other one.

**Comment by wongnata** [comment]
Thanks for reporting this! I have found a temporary workaround for this issue which I've documented [here](https://github.com/wongnata/PlayerDogModel_Plus/issues/47#issuecomment-2382134952), please let me know if this works for you, too!

The good news is [Digg is planning on fixing this issue in CruiserImproved in the future!](https://github.com/wongnata/PlayerDogModel_Plus/issues/47#issuecomment-2382192798)

**Comment by wongnata** [comment]
Let me know if/when you've tried the workaround and what the outcome ended up being! If it ends up being okay for you for now, I'll close this ticket!
